### ISSUE TITLE
ATAudioSessionPropertyManager.mm:359 FAILED to set property 1684431725 on AVAudioSession with error Error Domain=NSOSStatusErrorDomain Code=-50 "(null)"

### ISSUE THREAD

**Issue by 488taimoor** [flutter-webrtc/flutter-webrtc#1236] opened 2023-01-18 07:58 UTC
Describe the bug
I'm testing Flutter-webrtc-demo application with your provided flutter-webrtc-server.

I'm facing an issue on ios. Let me explain.
When I initiate a call first time everything works fine, but when I try to initiate a call second time I'm getting an error, and Audio is not working.

[as_client] AVAudioSession_iOS.mm:2374 Failed to set category, error: 'what'
[as_client] AVAudioSession_iOS.mm:2374 Failed to set category, error: -50
[as] ATAudioSessionPropertyManager.mm:359 FAILED to set property 1684431725 on AVAudioSession with error Error Domain=NSOSStatusErrorDomain Code=-50 "(null)"

To Reproduce

Expected behavior

Platform information
iphone 8 plus
os: 16.2

Flutter version:
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] VS Code (version 1.70.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
Plugin version:
OS:
OS version:
Thanks in advance.

**Comment by 488taimoor** [comment] 2023-01-18 08:03
@cloudwebrtc please have a look.

**Comment by 488taimoor** [comment] 2023-01-18 08:04
@davidzhao @hiroshihorie @ycherniavskyi

**Comment by hiroshihorie** [comment] 2023-01-18 09:01
Hi @488taimoor thanks for the report.
I'm looking into a bunch of audio issues , hopefully I can resolve this one also.

**Comment by hiroshihorie** [comment] 2023-01-20 06:36
Looks like duplicate of https://github.com/flutter-webrtc/flutter-webrtc/issues/1230

**Closed** 2023-01-20 06:39 UTC
Labels: 🐛bug

**Comment by DanielSelig** [comment] 2024-10-01 23:44
I fixed my problem by setting the session active before configuring it.

**Comment by ardeshir-33033** [comment] 2024-11-21 19:25
@DanielSelig 
can you explain more?
